### ISSUE TITLE
can you please convert this code in laravel 9 php 8.2 version

### ISSUE THREAD

**Issue by amitdevteams** [Gicehajunior/pdf-encrypt#9]

**Comment by Gicehajunior** [comment]
Yes. It's all possible. You need such?

**Comment by amitdevteams** [comment]
yes its needs please do it ASP

**Comment by Gicehajunior** [comment]
Please Drop an official request to my institution and we can plan to have you the laravel application of the same functionality. My developer email is, gicehajunior76@daphascomp.com or to my personal email, gicehajunior76@gmail.com.

Thanks.

**Comment by amitdevteams** [comment]
Email sent
